
modLoader="javafml" 
loaderVersion="${loader_version_range}" 
license="MIT"

[[mods]] 
modId="${mod_id}" 
version="${mod_version}"
displayName="${mod_name}"
logoFile="${logo_file}"
authors="${mod_authors}"

description='''${mod_description}'''

[[dependencies.bygonefortress]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.bygonefortress]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"